# Generated by Django 5.2.14 on 2026-05-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitinterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('repo_name', models.CharField(max_length=100)),
                ('embedding', models.TextField()),
                ('tree_sha', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repo_analysis',
            },
        ),
    ]
