# Generated by Django 5.2.14 on 2026-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitinterface', '0002_repo_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_analysis',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repo_analysis',
            name='embedding',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='repo_analysis',
            constraint=models.UniqueConstraint(fields=('user', 'repo_name'), name='unique_user_repo'),
        ),
    ]
