# Generated by Django 5.2.14 on 2026-05-21 12:27

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('gitinterface', '0003_alter_repo_analysis_content_and_more'),
    ]

    operations = [
        VectorExtension(),
    ]
