# Generated by Django 5.2.14 on 2026-05-21 12:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitinterface', '0004_auto_20260521_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_analysis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
