# Generated by Django 5.2.14 on 2026-05-21 13:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitinterface', '0005_alter_repo_analysis_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_analysis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
